# http://oid-info.com/get/1.3.6.1.4.1.25461.2
---
extends:
  - system-mib.yml
  - if-mib.yml
  - host-resources-mib.yml
  - ospf-mib.yml
  - tcp-mib.yml
  - udp-mib.yml
  - ip-mib.yml

sysobjectid: 1.3.6.1.4.1.25461.*

metrics:
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.1.0
      name: panSessionUtilization
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.2.0
      name: panSessionMax
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.3.0
      name: panSessionActive
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.4.0
      name: panSessionActiveTcp
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.5.0
      name: panSessionActiveUdp
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.6.0
      name: panSessionActiveICMP
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.7.0
      name: panSessionActiveSslProxy
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.3.8.0
      name: panSessionSslProxyUtilization
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.5.1.1.0
      name: panGPGWUtilizationPct
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.5.1.2.0
      name: panGPGWUtilizationMaxTunnels
  - MIB: PAN-COMMON-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.2.1.2.5.1.3.0
      name: panGPGWUtilizationActiveTunnels
  - MIB: PAN-ENTITY-EXT-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.1.1.7.1.1.2.0
      name: panEntityTotalPowerUsed
  - MIB: PAN-ENTITY-EXT-MIB
    symbol:
      OID: 1.3.6.1.4.1.25461.1.1.7.1.1.1.0
      name: panEntityTotalPowerAvail
  - MIB: PAN-ENTITY-EXT-MIB
    table:
      OID: 1.3.6.1.4.1.25461.1.1.7.1.2.1
      name: panEntityFRUModuleTable
    symbols:
      - OID: 1.3.6.1.4.1.25461.1.1.7.1.2.1.1.1
        name: panEntryFRUModulePowerUsed
      - OID: 1.3.6.1.4.1.25461.1.1.7.1.2.1.1.2
        name: panEntryFRUModuleNumPorts
    metric_tags:
      - MIB: ENTITY-MIB
        column:
          OID: 1.3.6.1.2.1.47.1.1.1.1.2
          name: entPhysicalDescr
        table: entPhysicalTable
        tag: entity_description
  - MIB: PAN-ENTITY-EXT-MIB
    table:
      OID: 1.3.6.1.4.1.25461.1.1.7.1.3.1
      name: panEntityFanTrayTable
    symbols:
      - OID: 1.3.6.1.4.1.25461.1.1.7.1.3.1.1.1
        name: panEntryFanTrayPowerUsed
    metric_tags:
      - MIB: ENTITY-MIB
        column:
          OID: 1.3.6.1.2.1.47.1.1.1.1.2
          name: entPhysicalDescr
        table: entPhysicalTable
        tag: entity_description
