# http://oid-info.com/get/1.3.6.1.4.1.14823.2
---
extends:
  - system-mib.yml
  - if-mib.yml
  - ospf-mib.yml

sysobjectid: 1.3.6.1.4.1.14823.*

metrics:
  - MIB: WLSX-SYSTEMEXT-MIB
    table:
      OID: 1.3.6.1.4.1.14823.2.2.1.2.1.17
      name: wlsxSysExtFanTable
    symbols:
      - OID: 1.3.6.1.4.1.14823.2.2.1.2.1.17.1.2
        name: sysExtFanStatus
        enum:
          active: 1
          inactive: 2
    metric_tags:
      - tag: fan_index
        column:
          OID: 1.3.6.1.4.1.14823.2.2.1.2.1.17.1.1
          name: sysExtFanIndex
  - MIB: WLSX-SYSTEMEXT-MIB
    table:
      OID: 1.3.6.1.4.1.14823.2.2.1.2.1.18
      name: wlsxSysExtPowerSupplyTable
    symbols:
      - OID: 1.3.6.1.4.1.14823.2.2.1.2.1.18.1.2
        name: sysExtPowerSupplyStatus
        enum:
          active: 1
          inactive: 2
    metric_tags:
      - tag: power_supply_index
        column:
          OID: 1.3.6.1.4.1.14823.2.2.1.2.1.18.1.1
          name: sysExtPowerSupplyIndex
  - MIB: WLSX-SYSTEMEXT-MIB
    symbol:
      OID: 1.3.6.1.4.1.14823.2.2.1.2.1.32.0
      name: wlsxSysExtPacketLossPercent
  - MIB: WLSX-SYSTEMEXT-MIB
    symbol:
      OID: 1.3.6.1.4.1.14823.2.2.1.2.1.30.0
      name: wlsxSysExtCpuUsedPercent
      tag: CPU
  - MIB: WLSX-SYSTEMEXT-MIB
    symbol:
      OID: 1.3.6.1.4.1.14823.2.2.1.2.1.31.0
      name: wlsxSysExtMemoryUsedPercent
      tag: MemoryUtilization
