# http://oid-info.com/get/1.3.6.1.2.1.2.2
# http://oid-info.com/get/1.3.6.1.2.1.31
metrics:
- MIB: IF-MIB
  table:
    OID: 1.3.6.1.2.1.2.2
    name: ifTable
  symbols:
  - OID: 1.3.6.1.2.1.2.2.1.14
    name: ifInErrors
  - OID: 1.3.6.1.2.1.2.2.1.13
    name: ifInDiscards
  - OID: 1.3.6.1.2.1.2.2.1.20
    name: ifOutErrors
  - OID: 1.3.6.1.2.1.2.2.1.19
    name: ifOutDiscards
  metric_tags:
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.1
      name: ifName
    table: ifXTable
    tag: interface_name
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.18
      name: ifAlias
    table: ifXTable
    tag: interface_alias
- MIB: IF-MIB
  table:
    OID: 1.3.6.1.2.1.2.2
    name: ifTable
  symbols:
  - OID: 1.3.6.1.2.1.2.2.1.7
    name: ifAdminStatus
    enum:
      up: 1
      down: 2
      testing: 3
  - OID: 1.3.6.1.2.1.2.2.1.8
    name: ifOperStatus
    enum:
      up: 1
      down: 2
      testing: 3
      unknown: 4
      dormant: 5
      notPresent: 6
      lowerLayerDown: 7
  metric_tags:
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.1
      name: ifName
      tag: interface_name
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.18
      name: ifAlias
      tag: interface_alias
- MIB: IF-MIB
  table:
    OID: 1.3.6.1.2.1.31.1.1
    name: ifXTable
  symbols:
  - OID: 1.3.6.1.2.1.31.1.1.1.7
    name: ifHCInUcastPkts
  - OID: 1.3.6.1.2.1.31.1.1.1.8
    name: ifHCInMulticastPkts
  - OID: 1.3.6.1.2.1.31.1.1.1.9
    name: ifHCInBroadcastPkts
  - OID: 1.3.6.1.2.1.31.1.1.1.11
    name: ifHCOutUcastPkts
  - OID: 1.3.6.1.2.1.31.1.1.1.12
    name: ifHCOutMulticastPkts
  - OID: 1.3.6.1.2.1.31.1.1.1.13
    name: ifHCOutBroadcastPkts
  metric_tags:
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.1
      name: ifName
    tag: interface_name
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.18
      name: ifAlias
    table: ifXTable
    tag: interface_alias
- MIB: IF-MIB
  table:
    OID: 1.3.6.1.2.1.31.1.1
    name: ifXTable
  symbols:
  - OID: 1.3.6.1.2.1.31.1.1.1.6
    name: ifHCInOctets
  - OID: 1.3.6.1.2.1.31.1.1.1.10
    name: ifHCOutOctets
  metric_tags:
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.1
      name: ifName
    tag: interface_name
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.18
      name: ifAlias
    tag: interface_alias
  - column:
      OID: 1.3.6.1.2.1.31.1.1.1.15
      name: ifHighSpeed
    tag: interface_speed
