# http://oid-info.com/get/1.3.6.1.2.1.1
---
metric_tags:
  - column:
      OID: 1.3.6.1.2.1.1.1.0
      name: sysDescr
    tag: snmp_sysdesc
  - column:
      OID: 1.3.6.1.2.1.1.2.0
      name: sysObjectID
    tag: snmp_sysobjectid
  - column:
      OID: 1.3.6.1.2.1.1.5.0
      name: sysName
    tag: snmp_sysname