# http://oid-info.com/get/1.3.6.1.2.1.7
---
metrics:
- MIB: UDP-MIB
  symbol:
    OID: 1.3.6.1.2.1.7.8.0
    name: udpHCInDatagrams
- MIB: UDP-MIB
  symbol:
    OID: 1.3.6.1.2.1.7.2.0
    name: udpNoPorts
- MIB: UDP-MIB
  symbol:
    OID: 1.3.6.1.2.1.7.3.0
    name: udpInErrors
- MIB: UDP-MIB
  symbol:
    OID: 1.3.6.1.2.1.7.9.0
    name: udpHCOutDatagrams
