version: "3.9"
services:
  influxdb:
    image: influxdb:2.2.0-alpine
    restart: always
    environment:
      - "DOCKER_INFLUXDB_INIT_MODE=setup"
      - "DOCKER_INFLUXDB_INIT_USERNAME=admin"
      - "DOCKER_INFLUXDB_INIT_PASSWORD=influxdb"
      - "DOCKER_INFLUXDB_INIT_ORG=system"
      - "DOCKER_INFLUXDB_INIT_BUCKET=default"
      - "DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=secret-token"
    healthcheck:
      test: ["CMD", "curl", "localhost:8086"]
      interval: 10s
      timeout: 1s
      retries: 30
      start_period: 10s
    ports:
      - 8086:8086

  ktranslate:
    image: kentik/ktranslate:v2
    command:
      - --sinks=http
      - --format=influx
      - --http_url
      - "http://influxdb:8086/api/v2/write?org=system&bucket=default"
      - --http_header
      - "Authorization: Token secret-token"
      - --http_header
      - "Content-type: application/json"
      - --nf.source=netflow5
      - --nf.addr=0.0.0.0
      - --nf.port=9995
    restart: always
    ports:
      - 9995:9995/udp
    depends_on:
      - influxdb

  nflow:
    image: ehazlett/nflow-generator:latest
    restart: always
    command:
      - -t
      - ktranslate
      - -p
      - "9995"
    depends_on:
      - ktranslate
