# http://oid-info.com/get/1.3.6.1.4.1.2636.3.1.13.1
---
extends:
  - system-mib.yml
  - if-mib.yml
  - ip-mib.yml
  - tcp-mib.yml
  - udp-mib.yml
  - bgp4-mib.yml
  - ospf-mib.yml
  - host-resources-mib.yml

sysobjectid:
  - 1.3.6.1.4.1.2636.1.1.1.*

metrics:
  - MIB: JUNIPER-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.1.13.1
      name: jnxOperatingEntry
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.1.13.1.8
        name: jnxOperatingCPU
        tag: CPU
      - OID: 1.3.6.1.4.1.2636.3.1.13.1.11
        name: jnxOperatingBuffer
        tag: MemoryUtilization
    metric_tags:
      - tag: chassis
        column:
          OID: 1.3.6.1.4.1.2636.3.1.13.1.18
          name: jnxOperatingChassisDescr
