# http://oid-info.com/get/1.3.6.1.4.1.2636.3.6.2
# http://oid-info.com/get/1.3.6.1.4.1.2636.3.5
# http://oid-info.com/get/1.3.6.1.4.1.2636.3.40.1.4.1
# http://oid-info.com/get/1.3.6.1.4.1.2636.3.15.10
---
extends:
  - juniper-all-devices.yml

sysobjectid:
  - 1.3.6.1.4.1.2636.1.1.1.2.30
  - 1.3.6.1.4.1.2636.1.1.1.4.30.*
  - 1.3.6.1.4.1.2636.1.1.1.2.31
  - 1.3.6.1.4.1.2636.1.1.1.4.31.*
  - 1.3.6.1.4.1.2636.1.1.1.2.32
  - 1.3.6.1.4.1.2636.1.1.1.4.32.*
  - 1.3.6.1.4.1.2636.1.1.1.2.33
  - 1.3.6.1.4.1.2636.1.1.1.4.33.*
  - 1.3.6.1.4.1.2636.1.1.1.2.43
  - 1.3.6.1.4.1.2636.1.1.1.4.43.*
  - 1.3.6.1.4.1.2636.1.1.1.2.44
  - 1.3.6.1.4.1.2636.1.1.1.4.44.*
  - 1.3.6.1.4.1.2636.1.1.1.2.74
  - 1.3.6.1.4.1.2636.1.1.1.4.74.*
  - 1.3.6.1.4.1.2636.1.1.1.2.76
  - 1.3.6.1.4.1.2636.1.1.1.4.76.*
  - 1.3.6.1.4.1.2636.1.1.1.2.131
  - 1.3.6.1.4.1.2636.1.1.1.4.131.*
  - 1.3.6.1.4.1.2636.1.1.1.2.132
  - 1.3.6.1.4.1.2636.1.1.1.4.132.*
  - 1.3.6.1.4.1.2636.1.1.1.2.151
  - 1.3.6.1.4.1.2636.1.1.1.4.151.*
  - 1.3.6.1.4.1.2636.1.1.1.2.156
  - 1.3.6.1.4.1.2636.1.1.1.4.156.*
  - 1.3.6.1.4.1.2636.1.1.1.2.165
  - 1.3.6.1.4.1.2636.1.1.1.4.165.*
  - 1.3.6.1.4.1.2636.1.1.1.2.508
  - 1.3.6.1.4.1.2636.1.1.1.4.508.*

metrics:
  - MIB: JUNIPER-DCU-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.6.2
      name: jnxDcuStatsTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.6.2.1.4
        name: jnxDcuStatsPackets
      - OID: 1.3.6.1.4.1.2636.3.6.2.1.5
        name: jnxDcuStatsBytes
    metric_tags:
      - column:
          OID: 1.3.6.1.2.1.31.1.1.1.1
          name: ifName
        table: ifXTable
        tag: interface_name
        index_transform:
          - start: 0
            end: 0
      - column:
          OID: 1.3.6.1.4.1.2636.3.6.2.1.2
          name: jnxDcuStatsAddrFamily
        tag: address_family
      - column:
          OID: 1.3.6.1.4.1.2636.3.6.2.1.3
          name: jnxDcuStatsClassName
        tag: destination_class_name
  - MIB: JUNIPER-FIREWALL-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.5.2
      name: jnxFirewallCounterTable
    symbols:
    - OID: 1.3.6.1.4.1.2636.3.5.2.1.4
      name: jnxFWCounterPacketCount
    - OID: 1.3.6.1.4.1.2636.3.5.2.1.5
      name: jnxFWCounterByteCount
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.1
        name: jnxFWCounterFilterName
      tag: firewall_filter_name
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.2
        name:  jnxFWCounterName
      tag: counter_name
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.3
        name: jnxFWCounterType
      tag: counter_type
  - MIB: JUNIPER-VIRTUALCHASSIS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2
      name: jnxVirtualChassisPortTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.5
        name: jnxVirtualChassisPortInPkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.6
        name: jnxVirtualChassisPortOutPkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.7
        name: jnxVirtualChassisPortInOctets
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.8
        name: jnxVirtualChassisPortOutOctets
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.9
        name: jnxVirtualChassisPortInMcasts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.10
        name: jnxVirtualChassisPortOutMcasts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.15
        name: jnxVirtualChassisPortCarrierTrans
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.16
        name: jnxVirtualChassisPortInCRCAlignErrors
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.17
        name: jnxVirtualChassisPortUndersizePkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.18
        name: jnxVirtualChassisPortCollisions
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.2
        name: jnxVirtualChassisPortName
      tag: port_name
  - MIB: JUNIPER-VIRTUALCHASSIS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2
      name: jnxVirtualChassisPortTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.11
        name: jnxVirtualChassisPortInPkts1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.12
        name: jnxVirtualChassisPortOutPkts1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.13
        name: jnxVirtualChassisPortInOctets1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.14
        name: jnxVirtualChassisPortOutOctets1secRate
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.2
        name: jnxVirtualChassisPortName
      tag: port_name
  - MIB: JUNIPER-COS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.15.10
      name: jnxCosIfsetQstatTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.3
        name: jnxCosIfsetQstatQedPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.5
        name: jnxCosIfsetQstatQedBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.7
        name: jnxCosIfsetQstatTxedPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.9
        name: jnxCosIfsetQstatTxedBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.11
        name: jnxCosIfsetQstatTailDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.13
        name: jnxCosIfsetQstatTotalRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.15
        name: jnxCosIfsetQstatLpNonTcpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.17
        name: jnxCosIfsetQstatLpTcpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.19
        name: jnxCosIfsetQstatHpNonTcpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.21
        name: jnxCosIfsetQstatHpTcpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.23
        name: jnxCosIfsetQstatTotalRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.25
        name: jnxCosIfsetQstatLpNonTcpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.27
        name: jnxCosIfsetQstatLpTcpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.29
        name: jnxCosIfsetQstatHpNonTcpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.31
        name: jnxCosIfsetQstatHpTcpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.33
        name: jnxCosIfsetQstatLpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.35
        name: jnxCosIfsetQstatMLpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.37
        name: jnxCosIfsetQstatMHpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.39
        name: jnxCosIfsetQstatHpRedDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.41
        name: jnxCosIfsetQstatLpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.43
        name: jnxCosIfsetQstatMLpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.45
        name: jnxCosIfsetQstatMHpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.47
        name: jnxCosIfsetQstatHpRedDropBytes
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.49
        name: jnxCosIfsetQstatRateLimitDropPkts
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.51
        name: jnxCosIfsetQstatRateLimitDropBytes
    metric_tags:
      - column:
          OID: 1.3.6.1.4.1.2636.3.15.9.1.2
          name: jnxCosIfsetDescr
        table: jnxCosIfTable
        tag: interface_name
        index_transform:
          - start: 0
            end: 0
      - column:
          OID: 1.3.6.1.4.1.2636.3.15.10.1.2
          name: jnxCosIfsetQstatQueueNr
        tag: queue_number
  - MIB: JUNIPER-COS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.15.10
      name: jnxCosIfsetQstatTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.4
        name: jnxCosIfsetQstatQedPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.6
        name: jnxCosIfsetQstatQedByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.8
        name: jnxCosIfsetQstatTxedPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.10
        name: jnxCosIfsetQstatTxedByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.12
        name: jnxCosIfsetQstatTailDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.14
        name: jnxCosIfsetQstatTotalRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.16
        name: jnxCosIfsetQstatLpNonTcpRDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.18
        name: jnxCosIfsetQstatLpTcpRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.20
        name: jnxCosIfsetQstatHpNonTcpRDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.22
        name: jnxCosIfsetQstatHpTcpRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.24
        name: jnxCosIfsetQstatTotalRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.26
        name: jnxCosIfsetQstatLpNonTcpRDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.28
        name: jnxCosIfsetQstatLpTcpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.30
        name: jnxCosIfsetQstatHpNonTcpRDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.32
        name: jnxCosIfsetQstatHpTcpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.34
        name: jnxCosIfsetQstatLpRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.36
        name: jnxCosIfsetQstatMLpRedDropPktRate
      - OID:  1.3.6.1.4.1.2636.3.15.10.1.38
        name: jnxCosIfsetQstatMHpRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.40
        name: jnxCosIfsetQstatHpRedDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.42
        name: jnxCosIfsetQstatLpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.44
        name: jnxCosIfsetQstatMLpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.46
        name: jnxCosIfsetQstatMHpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.48
        name: jnxCosIfsetQstatHpRedDropByteRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.50
        name: jnxCosIfsetQstatRateLimitDropPktRate
      - OID: 1.3.6.1.4.1.2636.3.15.10.1.52
        name: jnxCosIfsetQstatRateLimitDropByteRate
    metric_tags:
      - column:
          OID: 1.3.6.1.4.1.2636.3.15.9.1.2
          name: jnxCosIfsetDescr
        table: jnxCosIfTable
        tag: interface_name
        index_transform:
          - start: 0
            end: 0
      - column:
          OID: 1.3.6.1.4.1.2636.3.15.10.1.2
          name: jnxCosIfsetQstatQueueNr
        tag: queue_number
