# http://oid-info.com/get/1.3.6.1.4.1.2636.3.5
# http://oid-info.com/get/1.3.6.1.4.1.2636.3.40.1.4.1
---
extends:
  - system-mib.yml
  - if-mib.yml
  - ip-mib.yml
  - tcp-mib.yml
  - udp-mib.yml
  - bgp4-mib.yml
  - ospf-mib.yml
  - host-resources-mib.yml

sysobjectid:
  - 1.3.6.1.4.1.2636.1.1.1.2.21
  - 1.3.6.1.4.1.2636.1.1.1.4.21.*
  - 1.3.6.1.4.1.2636.1.1.1.2.25
  - 1.3.6.1.4.1.2636.1.1.1.4.25.*
  - 1.3.6.1.4.1.2636.1.1.1.2.29
  - 1.3.6.1.4.1.2636.1.1.1.4.29.*
  - 1.3.6.1.4.1.2636.1.1.1.2.57
  - 1.3.6.1.4.1.2636.1.1.1.4.57.*
  - 1.3.6.1.4.1.2636.1.1.1.2.88
  - 1.3.6.1.4.1.2636.1.1.1.4.88.*
  - 1.3.6.1.4.1.2636.1.1.1.2.89
  - 1.3.6.1.4.1.2636.1.1.1.4.89.*
  - 1.3.6.1.4.1.2636.1.1.1.2.90
  - 1.3.6.1.4.1.2636.1.1.1.4.90.*
  - 1.3.6.1.4.1.2636.1.1.1.2.93
  - 1.3.6.1.4.1.2636.1.1.1.4.93.*
  - 1.3.6.1.4.1.2636.1.1.1.2.97
  - 1.3.6.1.4.1.2636.1.1.1.4.97.*
  - 1.3.6.1.4.1.2636.1.1.1.2.99
  - 1.3.6.1.4.1.2636.1.1.1.4.99.*
  - 1.3.6.1.4.1.2636.1.1.1.2.145
  - 1.3.6.1.4.1.2636.1.1.1.4.145.*
  - 1.3.6.1.4.1.2636.1.1.1.2.146
  - 1.3.6.1.4.1.2636.1.1.1.4.146.*
  - 1.3.6.1.4.1.2636.1.1.1.2.154
  - 1.3.6.1.4.1.2636.1.1.1.4.154.*
  - 1.3.6.1.4.1.2636.1.1.1.2.155
  - 1.3.6.1.4.1.2636.1.1.1.4.155.*

metrics:
  - MIB: JUNIPER-FIREWALL-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.5.2
      name: jnxFirewallCounterTable
    symbols:
    - OID: 1.3.6.1.4.1.2636.3.5.2.1.4
      name: jnxFWCounterPacketCount
    - OID: 1.3.6.1.4.1.2636.3.5.2.1.5
      name: jnxFWCounterByteCount
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.1
        name: jnxFWCounterFilterName
      tag: firewall_filter_name
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.2
        name:  jnxFWCounterName
      tag: counter_name
    - column:
        OID: 1.3.6.1.4.1.2636.3.5.2.1.3
        name: jnxFWCounterType
      tag: counter_type
  - MIB: JUNIPER-VIRTUALCHASSIS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2
      name: jnxVirtualChassisPortTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.5
        name: jnxVirtualChassisPortInPkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.6
        name: jnxVirtualChassisPortOutPkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.7
        name: jnxVirtualChassisPortInOctets
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.8
        name: jnxVirtualChassisPortOutOctets
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.9
        name: jnxVirtualChassisPortInMcasts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.10
        name: jnxVirtualChassisPortOutMcasts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.15
        name: jnxVirtualChassisPortCarrierTrans
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.16
        name: jnxVirtualChassisPortInCRCAlignErrors
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.17
        name: jnxVirtualChassisPortUndersizePkts
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.18
        name: jnxVirtualChassisPortCollisions
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.2
        name: jnxVirtualChassisPortName
      tag: port_name
  - MIB: JUNIPER-VIRTUALCHASSIS-MIB
    table:
      OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2
      name: jnxVirtualChassisPortTable
    symbols:
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.11
        name: jnxVirtualChassisPortInPkts1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.12
        name: jnxVirtualChassisPortOutPkts1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.13
        name: jnxVirtualChassisPortInOctets1secRate
      - OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.14
        name: jnxVirtualChassisPortOutOctets1secRate
    metric_tags:
    - column:
        OID: 1.3.6.1.4.1.2636.3.40.1.4.1.2.1.2
        name: jnxVirtualChassisPortName
      tag: port_name
