name: RPM Build

on:
  push:
    branches:
      - main
      - make-rpm

jobs:
  build:
    runs-on: ubuntu-latest
    # There's several of these lists of releases that we're building
    # for scattered throughout these workflows. Hopefully one day GH
    # makes it possible to define this in one place and then refer to
    # it. In the meantime, if you're adding to this list, go look for
    # other "matrix" definitions.
    strategy:
      matrix:
        include:
          - distro: centos
            release: 8
    container:
      image: ${{ matrix.distro }}:${{ matrix.release }}

    # NB: any run steps that need chf src need to have `working-directory: ${{ env.SRCDIR }}`
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Version
        run: |
           echo KENTIK_KTRANSLATE_VERSION=`date +"kt-%Y-%m-%d-${GITHUB_RUN_ID}"` >> $GITHUB_ENV

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.3'

      - name: Get Deps
        run: |
          dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
          yum install -y make gcc diffutils

      - name: Run build
        run: |
          echo ${{ env.KENTIK_KTRANSLATE_VERSION }}
          KENTIK_KTRANSLATE_VERSION=${{ env.KENTIK_KTRANSLATE_VERSION }} go generate ./cmd/version
          KENTIK_KTRANSLATE_VERSION=${{ env.KENTIK_KTRANSLATE_VERSION }} go build -o bin/ktranslate ./cmd/ktranslate

      - name: Create package
        id: package
        uses: kentik/pkg@master
        with:
          name: ktranslate
          version: ${{ env.KENTIK_KTRANSLATE_VERSION }}
          arch: x86_64
          format: ${{ matrix.pkg }}
          package: ktranslate-package.yml
